<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'A valid consumer key, shared secret and public / private key pair must be provided' => '',
    'A valid public / private key pair must be provided' => '',
    'At least one argument must be supplied with the HTTP Method when calling "{command}"' => '',
    'The Xero API command "{command}" does not support the method "{method}"' => '',
    'The Xero Api has returned the following error:{errors}' => '',
    'The Xero OAuth call has returned the following errors:{errors}' => '',
    'The command "{command}" is not valid for the Xero API' => '',
    'Two parameters are required for method "{method}", the method and the XML data' => '',
];
